{
    "success":true,
    "code":1,
    "msg":"操作成功",
    "data":[
        {
            "questionID":60633,
            "content":"<p>黑板上原来有6个正方形，老师遮住了$$个正方形.</p><p><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/0c39406528b6087bb45be41871ca05f7.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/0c39406528b6087bb45be41871ca05f7.png"/></p>",
            "typeID":1,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153119",
                    "content":"1",
                    "sign":"A",
                    "isright":1
                },
                {
                    "answerID":"153121",
                    "content":"2",
                    "sign":"B",
                    "isright":2
                },
                {
                    "answerID":"153123",
                    "content":"3",
                    "sign":"C",
                    "isright":1
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153121",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                }
            ]
        },
        {
            "questionID":60632,
            "content":"兔子吃萝卜.<div><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/637db8ae292635c937b6f4c00aa0c9be.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/637db8ae292635c937b6f4c00aa0c9be.png"/></div><p>那么括号里依次填的数为$$，$$，$$，$$.</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153111",
                    "content":"4",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"153113",
                    "content":"5",
                    "sign":"B",
                    "isright":2
                },
                {
                    "answerID":"153115",
                    "content":"2",
                    "sign":"C",
                    "isright":2
                },
                {
                    "answerID":"153117",
                    "content":"7",
                    "sign":"D",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153111",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                },
                {
                    "answerID":"153113",
                    "answerContentHtml":"5",
                    "answerContent":"5"
                },
                {
                    "answerID":"153115",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                },
                {
                    "answerID":"153117",
                    "answerContentHtml":"7",
                    "answerContent":"7"
                }
            ]
        },
        {
            "questionID":60631,
            "content":"<p>填数，使每条线上的三个数相加都得6.</p><p><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/40d0e0dc01c53de96c60c2d1765f8bb9.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/40d0e0dc01c53de96c60c2d1765f8bb9.png"/></p><p>按照从上至下，再从左到右的填写顺序，圆圈中填的数分别是$$,$$,$$.</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153105",
                    "content":"2",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"153107",
                    "content":"4",
                    "sign":"B",
                    "isright":2
                },
                {
                    "answerID":"153109",
                    "content":"1",
                    "sign":"C",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153105",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                },
                {
                    "answerID":"153107",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                },
                {
                    "answerID":"153109",
                    "answerContentHtml":"1",
                    "answerContent":"1"
                }
            ]
        },
        {
            "questionID":60630,
            "content":"填数，使每条线上的三个数相加都得6.<div><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/86aa554d5a0fda0d380ec37c1a46f282.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/86aa554d5a0fda0d380ec37c1a46f282.png"/></div>按照从上至下，再从左到右的填写顺序，圆圈中填的数分别是$$,$$,$$.",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153099",
                    "content":"2",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"153101",
                    "content":"3",
                    "sign":"B",
                    "isright":2
                },
                {
                    "answerID":"153103",
                    "content":"1",
                    "sign":"C",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153099",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                },
                {
                    "answerID":"153101",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                },
                {
                    "answerID":"153103",
                    "answerContentHtml":"1",
                    "answerContent":"1"
                }
            ]
        },
        {
            "questionID":60629,
            "content":"填数，使每条线上的三个数相加都得6.<div><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/cbbf1038efb9b6521f1b8dcf88868c2c.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/cbbf1038efb9b6521f1b8dcf88868c2c.png"/></div><p>按照从上至下的填写顺序，圆圈中填的数分别是$$,$$,$$.</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153093",
                    "content":"1",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"153095",
                    "content":"2",
                    "sign":"B",
                    "isright":2
                },
                {
                    "answerID":"153097",
                    "content":"1",
                    "sign":"C",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153093",
                    "answerContentHtml":"1",
                    "answerContent":"1"
                },
                {
                    "answerID":"153095",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                },
                {
                    "answerID":"153097",
                    "answerContentHtml":"1",
                    "answerContent":"1"
                }
            ]
        },
        {
            "questionID":60628,
            "content":"填数，使每条线上的三个数相加都得7.<div><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/40d0e0dc01c53de96c60c2d1765f8bb9.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/40d0e0dc01c53de96c60c2d1765f8bb9.png"/></div><p>按照从上至下，再从左到右的填写顺序，圆圈中填的数分别是$$,$$,$$.</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153087",
                    "content":"3",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"153089",
                    "content":"4",
                    "sign":"B",
                    "isright":2
                },
                {
                    "answerID":"153091",
                    "content":"2",
                    "sign":"C",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153087",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                },
                {
                    "answerID":"153089",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                },
                {
                    "answerID":"153091",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                }
            ]
        },
        {
            "questionID":60627,
            "content":"填数，使每条线上的三个数相加都得7.<div><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/86aa554d5a0fda0d380ec37c1a46f282.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/86aa554d5a0fda0d380ec37c1a46f282.png"/></div><p>按照从上至下，再从左到右的填写顺序，圆圈中填的数分别是$$,$$,$$.</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153081",
                    "content":"3",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"153083",
                    "content":"4",
                    "sign":"B",
                    "isright":2
                },
                {
                    "answerID":"153085",
                    "content":"2",
                    "sign":"C",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153081",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                },
                {
                    "answerID":"153083",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                },
                {
                    "answerID":"153085",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                }
            ]
        },
        {
            "questionID":60626,
            "content":"<p>填数，使每条线上的三个数相加都得7.</p><p><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/cbbf1038efb9b6521f1b8dcf88868c2c.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/cbbf1038efb9b6521f1b8dcf88868c2c.png"/></p><p>按照从上至下的填写顺序，圆圈中填的数分别是$$,$$,$$.</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153075",
                    "content":"2",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"153077",
                    "content":"2",
                    "sign":"B",
                    "isright":2
                },
                {
                    "answerID":"153079",
                    "content":"2",
                    "sign":"C",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153075",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                },
                {
                    "answerID":"153077",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                },
                {
                    "answerID":"153079",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                }
            ]
        },
        {
            "questionID":60625,
            "content":"<img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/ceacf404baea7df1edb8f9abf2c8c3f6.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/ceacf404baea7df1edb8f9abf2c8c3f6.png"/><p>横向和竖向之和都为7，请问第一行第三列的数是$$.</p>",
            "typeID":1,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153067",
                    "content":"2",
                    "sign":"A",
                    "isright":1
                },
                {
                    "answerID":"153069",
                    "content":"3",
                    "sign":"B",
                    "isright":2
                },
                {
                    "answerID":"153071",
                    "content":"4",
                    "sign":"C",
                    "isright":1
                },
                {
                    "answerID":"153073",
                    "content":"5",
                    "sign":"D",
                    "isright":1
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153069",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                }
            ]
        },
        {
            "questionID":60624,
            "content":"<p><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/ceacf404baea7df1edb8f9abf2c8c3f6.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/ceacf404baea7df1edb8f9abf2c8c3f6.png"/></p><p>横向和竖向之和都为7，请问第二行第三列的数是$$.</p>",
            "typeID":1,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153059",
                    "content":"2",
                    "sign":"A",
                    "isright":1
                },
                {
                    "answerID":"153061",
                    "content":"3",
                    "sign":"B",
                    "isright":2
                },
                {
                    "answerID":"153063",
                    "content":"4",
                    "sign":"C",
                    "isright":1
                },
                {
                    "answerID":"153065",
                    "content":"5",
                    "sign":"D",
                    "isright":1
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153061",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                }
            ]
        },
        {
            "questionID":60623,
            "content":"<img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/3755a27336b31e83ba9269a80c7090f1.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/3755a27336b31e83ba9269a80c7090f1.png"/><p>横向和竖向之和都为7，请问第二行第三列的数是$$.</p>",
            "typeID":1,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153051",
                    "content":"2",
                    "sign":"A",
                    "isright":1
                },
                {
                    "answerID":"153053",
                    "content":"3",
                    "sign":"B",
                    "isright":1
                },
                {
                    "answerID":"153055",
                    "content":"4",
                    "sign":"C",
                    "isright":1
                },
                {
                    "answerID":"153057",
                    "content":"5",
                    "sign":"D",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153057",
                    "answerContentHtml":"5",
                    "answerContent":"5"
                }
            ]
        },
        {
            "questionID":60622,
            "content":"<img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/3755a27336b31e83ba9269a80c7090f1.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/3755a27336b31e83ba9269a80c7090f1.png"/><p>横向和竖向之和都为7，请问第一行第三列的数是$$.</p>",
            "typeID":1,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153043",
                    "content":"1",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"153045",
                    "content":"2",
                    "sign":"B",
                    "isright":1
                },
                {
                    "answerID":"153047",
                    "content":"3",
                    "sign":"C",
                    "isright":1
                },
                {
                    "answerID":"153049",
                    "content":"4",
                    "sign":"D",
                    "isright":1
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153043",
                    "answerContentHtml":"1",
                    "answerContent":"1"
                }
            ]
        },
        {
            "questionID":60621,
            "content":"<img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/2864be01d437e2e3bd8244908860c5e2.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/2864be01d437e2e3bd8244908860c5e2.png"/><p>中间的数等于周围数之和，则框中所填的数为$$.</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153041",
                    "content":"6",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153041",
                    "answerContentHtml":"6",
                    "answerContent":"6"
                }
            ]
        },
        {
            "questionID":60620,
            "content":"<img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/98fd85810ae4de7031d57414225e5285.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/98fd85810ae4de7031d57414225e5285.png"/><p>中间的数等于周围数之和，则框中所填的数为$$.</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153039",
                    "content":"7",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153039",
                    "answerContentHtml":"7",
                    "answerContent":"7"
                }
            ]
        },
        {
            "questionID":60619,
            "content":"<img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/e80dba6ad8da8889c52fce1a7f78ee1d.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/e80dba6ad8da8889c52fce1a7f78ee1d.png"/><p>中间的数等于周围同色数的和与异色数之差，则框中所填的数为$$.</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153037",
                    "content":"3",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153037",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                }
            ]
        },
        {
            "questionID":60618,
            "content":"<img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/f6ca2e3e1796a878a7be15103da0b277.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/f6ca2e3e1796a878a7be15103da0b277.png"/><p>中间的数等于周围同色数的和与异色数之差，则框中所填的数为$$.</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153035",
                    "content":"3",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153035",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                }
            ]
        },
        {
            "questionID":60617,
            "content":"<p>波波帮妈妈去排队买早餐，她排在最后且前面有5人，队伍总共有$$人.</p>",
            "typeID":1,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153027",
                    "content":"4",
                    "sign":"A",
                    "isright":1
                },
                {
                    "answerID":"153029",
                    "content":"5",
                    "sign":"B",
                    "isright":1
                },
                {
                    "answerID":"153031",
                    "content":"6",
                    "sign":"C",
                    "isright":2
                },
                {
                    "answerID":"153033",
                    "content":"7",
                    "sign":"D",
                    "isright":1
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153031",
                    "answerContentHtml":"6",
                    "answerContent":"6"
                }
            ]
        },
        {
            "questionID":60616,
            "content":"<p>波波帮妈妈去排队买早餐，她前面有2人且后面有4人，队伍总共有$$人.</p>",
            "typeID":1,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153019",
                    "content":"4",
                    "sign":"A",
                    "isright":1
                },
                {
                    "answerID":"153021",
                    "content":"5",
                    "sign":"B",
                    "isright":1
                },
                {
                    "answerID":"153023",
                    "content":"6",
                    "sign":"C",
                    "isright":1
                },
                {
                    "answerID":"153025",
                    "content":"7",
                    "sign":"D",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153025",
                    "answerContentHtml":"7",
                    "answerContent":"7"
                }
            ]
        },
        {
            "questionID":60615,
            "content":"<p>波波帮妈妈去排队买早餐，有7个人在排队，波波后面有2人，则波波排在第$$位.</p>",
            "typeID":1,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153011",
                    "content":"3",
                    "sign":"A",
                    "isright":1
                },
                {
                    "answerID":"153013",
                    "content":"4",
                    "sign":"B",
                    "isright":1
                },
                {
                    "answerID":"153015",
                    "content":"5",
                    "sign":"C",
                    "isright":2
                },
                {
                    "answerID":"153017",
                    "content":"6",
                    "sign":"D",
                    "isright":1
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153015",
                    "answerContentHtml":"5",
                    "answerContent":"5"
                }
            ]
        },
        {
            "questionID":60614,
            "content":"<p>波波帮妈妈去排队买早餐，有7个人在排队，波波前面有2人，则波波排在第$$位.</p>",
            "typeID":1,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"153003",
                    "content":"2",
                    "sign":"A",
                    "isright":1
                },
                {
                    "answerID":"153005",
                    "content":"3",
                    "sign":"B",
                    "isright":2
                },
                {
                    "answerID":"153007",
                    "content":"4",
                    "sign":"C",
                    "isright":1
                },
                {
                    "answerID":"153009",
                    "content":"5",
                    "sign":"D",
                    "isright":1
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"153005",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                }
            ]
        },
        {
            "questionID":60613,
            "content":"根据图中的信息，将式子补充完整.<div><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/0c831e6481772f03ad25ef9d7e7ac7be.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/0c831e6481772f03ad25ef9d7e7ac7be.png"/></div><div>    $$－$$＝3</div>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152999",
                    "content":"7",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"153001",
                    "content":"4",
                    "sign":"B",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152999",
                    "answerContentHtml":"7",
                    "answerContent":"7"
                },
                {
                    "answerID":"153001",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                }
            ]
        },
        {
            "questionID":60612,
            "content":"<p class="1"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning:0pt">把下面算式按得数从大到小的顺序排列<span lang="EN-US">.</span>（填数字）<span lang="EN-US"><o:p></o:p></span></span></p><p class="MsoNormal"><span lang="EN-US" style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast">1</span><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast">、<span lang="EN-US">6+1   2</span>、<span lang="EN-US">7-1   3</span>、<span lang="EN-US">7-2   4</span>、<span lang="EN-US">5-2<o:p></o:p></span></span></p><p class="MsoNormal"><span>$$＞$$＞$$＞$$</span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152991",
                    "content":"1",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152993",
                    "content":"2",
                    "sign":"B",
                    "isright":2
                },
                {
                    "answerID":"152995",
                    "content":"3",
                    "sign":"C",
                    "isright":2
                },
                {
                    "answerID":"152997",
                    "content":"4",
                    "sign":"D",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152991",
                    "answerContentHtml":"1",
                    "answerContent":"1"
                },
                {
                    "answerID":"152993",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                },
                {
                    "answerID":"152995",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                },
                {
                    "answerID":"152997",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                }
            ]
        },
        {
            "questionID":60611,
            "content":"<p><span style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-theme-font:minor-fareast; mso-hansi-theme-font:minor-fareast;mso-bidi-font-family:"Times New Roman"; mso-bidi-theme-font:minor-bidi;mso-font-kerning:1.0pt;mso-ansi-language:EN-US; mso-fareast-language:ZH-CN;mso-bidi-language:AR-SA">看图填数<span lang="EN-US">.</span></span></p><div><span style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-theme-font:minor-fareast; mso-hansi-theme-font:minor-fareast;mso-bidi-font-family:"Times New Roman"; mso-bidi-theme-font:minor-bidi;mso-font-kerning:1.0pt;mso-ansi-language:EN-US; mso-fareast-language:ZH-CN;mso-bidi-language:AR-SA"><span lang="EN-US"><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2016/8/27/9acf51ede4d6c74bf6596816e2792e31.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2016/8/27/9acf51ede4d6c74bf6596816e2792e31.png"/></span></span></div><div><span lang="EN-US" style="font-size:12.0pt;font-family: 宋体;mso-ascii-theme-font:minor-fareast;mso-fareast-theme-font:minor-fareast; mso-hansi-theme-font:minor-fareast;mso-bidi-font-family:宋体;mso-ansi-language: EN-US;mso-fareast-language:ZH-CN;mso-bidi-language:AR-SA"><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2016/8/27/8058c527861beb3942a3893dcd1594ec.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2016/8/27/8058c527861beb3942a3893dcd1594ec.png"/>=</span><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font:minor-fareast; mso-bidi-font-family:宋体;mso-ansi-language:EN-US;mso-fareast-language:ZH-CN; mso-bidi-language:AR-SA">$$个<img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2016/8/27/44bfa334b731148733cd06d767143bbb.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2016/8/27/44bfa334b731148733cd06d767143bbb.png"/></span></div>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152989",
                    "content":"5",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152989",
                    "answerContentHtml":"5",
                    "answerContent":"5"
                }
            ]
        },
        {
            "questionID":60610,
            "content":"<p class="2" style="margin-left:18.0pt;text-indent:-18.0pt;mso-char-indent-count: 0;mso-list:l0 level1 lfo1"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning:0pt">根据图中的信息，将式子补充完整<span lang="EN-US">.<o:p></o:p></span></span></p><p class="2" style="margin-left:18.0pt;text-indent:-18.0pt;mso-char-indent-count: 0;mso-list:l0 level1 lfo1"><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2016/9/10/4d7d2cb5ba38a1d99a819718eb90cc5f.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2016/9/10/4d7d2cb5ba38a1d99a819718eb90cc5f.png"/></p><p class="MsoNormal"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font: minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast; mso-hansi-theme-font:minor-fareast">$$</span><span lang="EN-US" style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning:0pt">-</span><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning:0pt">$$<span lang="EN-US">=</span></span><span lang="EN-US" style="font-size:12.0pt;font-family: 宋体;mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast">2<o:p></o:p></span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152985",
                    "content":"6",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152987",
                    "content":"4",
                    "sign":"B",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152985",
                    "answerContentHtml":"6",
                    "answerContent":"6"
                },
                {
                    "answerID":"152987",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                }
            ]
        },
        {
            "questionID":60609,
            "content":"<p class="2"><span>根据图中的信息，将式子补充完整</span>.</p><p class="2"><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2016/8/27/251c142e583e80fb7a8c1fe9c9eb1c40.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2016/8/27/251c142e583e80fb7a8c1fe9c9eb1c40.png"/></span></p><p><span>$$</span><span >-</span><span>$$</span>=5</span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152981",
                    "content":"7",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152983",
                    "content":"2",
                    "sign":"B",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152981",
                    "answerContentHtml":"7",
                    "answerContent":"7"
                },
                {
                    "answerID":"152983",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                }
            ]
        },
        {
            "questionID":60608,
            "content":"<p class="2"><span>根据图中的信息，将式子补充完整<span lang="EN-US">.<o:p></o:p></span></span></p><p class="2"><span><span lang="EN-US"><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2016/8/27/69033b75eed1f3969e70a91f3762597c.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2016/8/27/69033b75eed1f3969e70a91f3762597c.png"/></span></span></p><p class="2"><span><span lang="EN-US"><span>2</span><span>+$$</span><span><span>=</span>$$</span></span></span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152977",
                    "content":"4",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152979",
                    "content":"6",
                    "sign":"B",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152977",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                },
                {
                    "answerID":"152979",
                    "answerContentHtml":"6",
                    "answerContent":"6"
                }
            ]
        },
        {
            "questionID":60607,
            "content":"<p class="2" style="margin-left:18.0pt;text-indent:-18.0pt;mso-char-indent-count: 0;mso-list:l0 level1 lfo1"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning:0pt">根据图中的信息，将式子补充完整<span lang="EN-US">.<o:p></o:p></span></span></p><p class="2" style="margin-left:18.0pt;text-indent:-18.0pt;mso-char-indent-count: 0;mso-list:l0 level1 lfo1"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning:0pt"><span lang="EN-US"><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2016/8/27/b1e96f84f3d5f831cdd1f141933c1138.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2016/8/27/b1e96f84f3d5f831cdd1f141933c1138.png"/></span></span></p><p class="MsoNormal"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font: minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast; mso-hansi-theme-font:minor-fareast">$$</span><span lang="EN-US" style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning:0pt">+</span><span lang="EN-US" style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast">3=</span><span style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast">$$<span lang="EN-US"><o:p></o:p></span></span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152973",
                    "content":"4",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152975",
                    "content":"7",
                    "sign":"B",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152973",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                },
                {
                    "answerID":"152975",
                    "answerContentHtml":"7",
                    "answerContent":"7"
                }
            ]
        },
        {
            "questionID":60606,
            "content":"<p><span><span>3+</span>$$<span>=2</span></span><span>+$$</span><span><span>=1</span></span><span>+</span><span>6<o:p></o:p></span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152969",
                    "content":"4",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152971",
                    "content":"5",
                    "sign":"B",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152969",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                },
                {
                    "answerID":"152971",
                    "answerContentHtml":"5",
                    "answerContent":"5"
                }
            ]
        },
        {
            "questionID":60605,
            "content":"3+3=$$+4=1+$$",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152965",
                    "content":"2",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152967",
                    "content":"5",
                    "sign":"B",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152965",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                },
                {
                    "answerID":"152967",
                    "answerContentHtml":"5",
                    "answerContent":"5"
                }
            ]
        },
        {
            "questionID":60604,
            "content":"<p class="MsoNormal"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font: minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast; mso-hansi-theme-font:minor-fareast">$$<span lang="EN-US">+4=2</span></span><span lang="EN-US" style="font-size:12.0pt; font-family:宋体;mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体; mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font:minor-fareast; mso-bidi-font-family:宋体;mso-font-kerning:0pt">+</span><span lang="EN-US" style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast">3=</span><span style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast">$$</span><span lang="EN-US" style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning:0pt">+</span><span lang="EN-US" style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast">2<o:p></o:p></span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152961",
                    "content":"1",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152963",
                    "content":"3",
                    "sign":"B",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152961",
                    "answerContentHtml":"1",
                    "answerContent":"1"
                },
                {
                    "answerID":"152963",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                }
            ]
        },
        {
            "questionID":60603,
            "content":"<p class="MsoNormal"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font: minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast; mso-hansi-theme-font:minor-fareast">$$<span lang="EN-US">-4=</span>$$</span><span lang="EN-US" style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning:0pt">+</span><span lang="EN-US" style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast">1=6-3</span><span lang="EN-US" style="font-size:12.0pt;font-family: 宋体;mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast;mso-bidi-font-family:宋体; mso-font-kerning:0pt"><o:p></o:p></span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152957",
                    "content":"7",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152959",
                    "content":"2",
                    "sign":"B",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152957",
                    "answerContentHtml":"7",
                    "answerContent":"7"
                },
                {
                    "answerID":"152959",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                }
            ]
        },
        {
            "questionID":60602,
            "content":"<p class="2" style="margin-left:18.0pt;text-indent:-18.0pt;mso-char-indent-count: 0;mso-list:l0 level1 lfo1"><span style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast;mso-bidi-font-family:宋体; mso-font-kerning:0pt">根据图中的信息，将式子补充完整<span lang="EN-US">.</span></span><span lang="EN-US"><o:p></o:p></span></p><p class="2" style="margin-left:18.0pt;text-indent:-18.0pt;mso-char-indent-count: 0;mso-list:l0 level1 lfo1"><span style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast;mso-bidi-font-family:宋体; mso-font-kerning:0pt"><span lang="EN-US"><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/9bfc6a2341dd7ef7f407062e25bf40ff.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/9bfc6a2341dd7ef7f407062e25bf40ff.png"/></span></span></p><p class="MsoNormal"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font: minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast; mso-hansi-theme-font:minor-fareast"><span lang="EN-US">3+</span>$$<span lang="EN-US">=</span>$$</span></p><p class="MsoNormal">$$-$$<span lang="EN-US">=3</span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152949",
                    "content":"4",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152951",
                    "content":"7",
                    "sign":"B",
                    "isright":2
                },
                {
                    "answerID":"152953",
                    "content":"7",
                    "sign":"C",
                    "isright":2
                },
                {
                    "answerID":"152955",
                    "content":"4",
                    "sign":"D",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152949",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                },
                {
                    "answerID":"152951",
                    "answerContentHtml":"7",
                    "answerContent":"7"
                },
                {
                    "answerID":"152953",
                    "answerContentHtml":"7",
                    "answerContent":"7"
                },
                {
                    "answerID":"152955",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                }
            ]
        },
        {
            "questionID":60601,
            "content":"<p class="2" style="margin-left:18.0pt;text-indent:-18.0pt;mso-char-indent-count: 0;mso-list:l0 level1 lfo1"><span>根据图中的信息，将式子补充完整</span><span lang="EN-US">.</span></p><p class="2" style="margin-left:18.0pt;text-indent:-18.0pt;mso-char-indent-count: 0;mso-list:l0 level1 lfo1"><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/7e602e82e865ea93228d922d880b4f8e.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/7e602e82e865ea93228d922d880b4f8e.png"/></p><p class="MsoNormal"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font: minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast; mso-hansi-theme-font:minor-fareast">$$<span lang="EN-US">+2=</span>$$<span lang="EN-US"><o:p></o:p></span></span></p><p class="2" style="margin-left:18.0pt;text-indent:-18.0pt;mso-char-indent-count: 0;mso-list:l0 level1 lfo1"><span lang="EN-US"></span></p><p class="MsoNormal"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font: minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast; mso-hansi-theme-font:minor-fareast"><span lang="EN-US">6-</span>$$<span lang="EN-US">=</span>4<span lang="EN-US"><o:p></o:p></span></span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152943",
                    "content":"4",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152945",
                    "content":"6",
                    "sign":"B",
                    "isright":2
                },
                {
                    "answerID":"152947",
                    "content":"2",
                    "sign":"C",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152943",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                },
                {
                    "answerID":"152945",
                    "answerContentHtml":"6",
                    "answerContent":"6"
                },
                {
                    "answerID":"152947",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                }
            ]
        },
        {
            "questionID":60600,
            "content":"<p class="MsoNormal"><span><span lang="EN-US">2+4</span>$$<span lang="EN-US">6-1</span></span></p><p class="MsoNormal"><br/></p>",
            "typeID":1,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152937",
                    "content":">",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152939",
                    "content":"<",
                    "sign":"B",
                    "isright":1
                },
                {
                    "answerID":"152941",
                    "content":"=",
                    "sign":"C",
                    "isright":1
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152937",
                    "answerContentHtml":">",
                    "answerContent":">"
                }
            ]
        },
        {
            "questionID":60599,
            "content":"<p class="MsoNormal"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast"><span lang="EN-US">7+0</span>$$<span lang="EN-US">4+3<o:p></o:p></span></span></p><p class="MsoNormal"><br/></p>",
            "typeID":1,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152931",
                    "content":">",
                    "sign":"A",
                    "isright":1
                },
                {
                    "answerID":"152933",
                    "content":"<",
                    "sign":"B",
                    "isright":1
                },
                {
                    "answerID":"152935",
                    "content":"=",
                    "sign":"C",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152935",
                    "answerContentHtml":"=",
                    "answerContent":"="
                }
            ]
        },
        {
            "questionID":60598,
            "content":"<p class="MsoNormal"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast"><span lang="EN-US">6-2</span>$$<span lang="EN-US">5-3<o:p></o:p></span></span></p><p class="MsoNormal"><br/></p>",
            "typeID":1,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152925",
                    "content":">",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152927",
                    "content":"<",
                    "sign":"B",
                    "isright":1
                },
                {
                    "answerID":"152929",
                    "content":"=",
                    "sign":"C",
                    "isright":1
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152925",
                    "answerContentHtml":">",
                    "answerContent":">"
                }
            ]
        },
        {
            "questionID":60597,
            "content":"<p class="MsoNormal"><span lang="EN-US" style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast">6-3</span><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast">$$<span lang="EN-US">5+2<o:p></o:p></span></span></p><p class="MsoNormal"><br/></p>",
            "typeID":1,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152919",
                    "content":">",
                    "sign":"A",
                    "isright":1
                },
                {
                    "answerID":"152921",
                    "content":"<",
                    "sign":"B",
                    "isright":2
                },
                {
                    "answerID":"152923",
                    "content":"=",
                    "sign":"C",
                    "isright":1
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152921",
                    "answerContentHtml":"<",
                    "answerContent":"<"
                }
            ]
        },
        {
            "questionID":60596,
            "content":"<p class="MsoNormal"><span lang="EN-US" style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast">3+2$$1+3<o:p></o:p></span></p><p class="MsoNormal"><br/></p>",
            "typeID":1,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152913",
                    "content":">",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152915",
                    "content":"<",
                    "sign":"B",
                    "isright":1
                },
                {
                    "answerID":"152917",
                    "content":"=",
                    "sign":"C",
                    "isright":1
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152913",
                    "answerContentHtml":">",
                    "answerContent":">"
                }
            ]
        },
        {
            "questionID":60595,
            "content":"<p class="MsoNormal"><span lang="EN-US" style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast">4+1$$6-1<o:p></o:p></span></p><p class="MsoNormal"><br/></p>",
            "typeID":1,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152907",
                    "content":">",
                    "sign":"A",
                    "isright":1
                },
                {
                    "answerID":"152909",
                    "content":"<",
                    "sign":"B",
                    "isright":1
                },
                {
                    "answerID":"152911",
                    "content":"=",
                    "sign":"C",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152911",
                    "answerContentHtml":"=",
                    "answerContent":"="
                }
            ]
        },
        {
            "questionID":60594,
            "content":"<p class="MsoNormal"><span lang="EN-US" style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast">2+4$$5+1<o:p></o:p></span></p><p class="MsoNormal"><br/></p>",
            "typeID":1,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152901",
                    "content":">",
                    "sign":"A",
                    "isright":1
                },
                {
                    "answerID":"152903",
                    "content":"<",
                    "sign":"B",
                    "isright":1
                },
                {
                    "answerID":"152905",
                    "content":"=",
                    "sign":"C",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152905",
                    "answerContentHtml":"=",
                    "answerContent":"="
                }
            ]
        },
        {
            "questionID":60593,
            "content":"<p><span style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-theme-font:minor-fareast; mso-hansi-theme-font:minor-fareast;mso-bidi-font-family:宋体;mso-ansi-language: EN-US;mso-fareast-language:ZH-CN;mso-bidi-language:AR-SA">根据图中的信息，将式子补充完整<span lang="EN-US">.</span></span></p><div><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2016/9/10/33095b9eef66c4a6a3727c2587f55bea.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2016/9/10/33095b9eef66c4a6a3727c2587f55bea.png"/></div><div><span style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-theme-font:minor-fareast; mso-hansi-theme-font:minor-fareast;mso-bidi-font-family:宋体;mso-ansi-language: EN-US;mso-fareast-language:ZH-CN;mso-bidi-language:AR-SA"><span lang="EN-US"></span></span><span> $$<span lang="EN-US">-</span>$$<span lang="EN-US">=</span></span><span lang="EN-US">3</span></div><p class="MsoNormal"><span lang="EN-US" style="font-size:12.0pt;font-family: 宋体;mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast;mso-bidi-font-family:宋体; mso-font-kerning:0pt"><o:p></o:p></span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152897",
                    "content":"7",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152899",
                    "content":"4",
                    "sign":"B",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152897",
                    "answerContentHtml":"7",
                    "answerContent":"7"
                },
                {
                    "answerID":"152899",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                }
            ]
        },
        {
            "questionID":60592,
            "content":"<p class="MsoNormal"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font: minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast; mso-hansi-theme-font:minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning: 0pt">根据图中的信息，将式子补充完整<span lang="EN-US">.<o:p></o:p></span></span></p><p class="MsoNormal"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font: minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast; mso-hansi-theme-font:minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning: 0pt"><span lang="EN-US"><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/fcb6814bfd8dedf2f4a7fee4c10bde39.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/fcb6814bfd8dedf2f4a7fee4c10bde39.png"/></span></span></p><p class="MsoNormal" align="left"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning:0pt">$$<span lang="EN-US">+</span></span><span lang="EN-US" style="font-size:12.0pt;font-family: 宋体;mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast">3=</span><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast">$$</span><span lang="EN-US" style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning:0pt"><o:p></o:p></span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152893",
                    "content":"4",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152895",
                    "content":"7",
                    "sign":"B",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152893",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                },
                {
                    "answerID":"152895",
                    "answerContentHtml":"7",
                    "answerContent":"7"
                }
            ]
        },
        {
            "questionID":60591,
            "content":"<p><span style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-theme-font:minor-fareast; mso-hansi-theme-font:minor-fareast;mso-bidi-font-family:宋体;mso-ansi-language: EN-US;mso-fareast-language:ZH-CN;mso-bidi-language:AR-SA">根据图中的信息，将式子补充完整<span lang="EN-US">.</span></span></p><div><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/526971bfb46c6098e8bfe125cad45742.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/526971bfb46c6098e8bfe125cad45742.png"/></div><div><p class="MsoNormal"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font: minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast; mso-hansi-theme-font:minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning: 0pt">$$<span lang="EN-US">-</span></span><span lang="EN-US" style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast">3=</span><span style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast">$$</span><span lang="EN-US" style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning:0pt"><o:p></o:p></span></p></div>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152889",
                    "content":"6",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152891",
                    "content":"3",
                    "sign":"B",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152889",
                    "answerContentHtml":"6",
                    "answerContent":"6"
                },
                {
                    "answerID":"152891",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                }
            ]
        },
        {
            "questionID":60590,
            "content":"<p class="MsoNormal" align="left"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning:0pt">兔子吃萝卜<span lang="EN-US">.<o:p></o:p></span></span></p><p class="MsoNormal" align="left"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning:0pt"><span lang="EN-US"><img src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/dc76b6afa920b222b68fb9b9d1692ead.png" _src="http://7xw2gq.com1.z0.glb.clouddn.com/head/2017/4/5/dc76b6afa920b222b68fb9b9d1692ead.png"/></span></span></p><p class="MsoNormal" align="left"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning:0pt"><span lang="EN-US"><span>那么括号里依次填的数为$$，$$，$$，$$</span>.</span></span></p><p class="MsoNormal" align="left"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast;mso-bidi-font-family:宋体;mso-font-kerning:0pt"><span lang="EN-US"><o:p></o:p></span></span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152881",
                    "content":"5",
                    "sign":"A",
                    "isright":2
                },
                {
                    "answerID":"152883",
                    "content":"7",
                    "sign":"B",
                    "isright":2
                },
                {
                    "answerID":"152885",
                    "content":"3",
                    "sign":"C",
                    "isright":2
                },
                {
                    "answerID":"152887",
                    "content":"6",
                    "sign":"D",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152881",
                    "answerContentHtml":"5",
                    "answerContent":"5"
                },
                {
                    "answerID":"152883",
                    "answerContentHtml":"7",
                    "answerContent":"7"
                },
                {
                    "answerID":"152885",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                },
                {
                    "answerID":"152887",
                    "answerContentHtml":"6",
                    "answerContent":"6"
                }
            ]
        },
        {
            "questionID":60589,
            "content":"<p class="2" style="margin-left:21.0pt;text-indent:-21.0pt;mso-char-indent-count: 0;mso-list:l0 level1 lfo1"><span lang="EN-US" style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast">2+</span><span style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast">$$<span lang="EN-US">=4+3<o:p></o:p></span></span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152879",
                    "content":"5",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152879",
                    "answerContentHtml":"5",
                    "answerContent":"5"
                }
            ]
        },
        {
            "questionID":60588,
            "content":"<p class="2" style="margin-left:21.0pt;text-indent:-21.0pt;mso-char-indent-count: 0;mso-list:l0 level1 lfo1"><span lang="EN-US" style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast">7-4=2+</span><span style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast">$$<span lang="EN-US"><o:p></o:p></span></span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152877",
                    "content":"1",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152877",
                    "answerContentHtml":"1",
                    "answerContent":"1"
                }
            ]
        },
        {
            "questionID":60587,
            "content":"<p class="2" style="margin-left:21.0pt;text-indent:-21.0pt;mso-char-indent-count: 0;mso-list:l0 level1 lfo1"><span lang="EN-US">1+5=</span><span>$$<span lang="EN-US">+3</span></span></p><p class="2" style="margin-left:21.0pt;text-indent:-21.0pt;mso-char-indent-count: 0;mso-list:l0 level1 lfo1"><span style="font-size:12.0pt;font-family:宋体; mso-ascii-theme-font:minor-fareast;mso-fareast-font-family:宋体;mso-fareast-theme-font: minor-fareast;mso-hansi-theme-font:minor-fareast"><span lang="EN-US"><o:p></o:p></span></span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152875",
                    "content":"3",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152875",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                }
            ]
        },
        {
            "questionID":60586,
            "content":"<p class="2" style="margin-left:21.0pt;text-indent:-21.0pt;mso-char-indent-count: 0;mso-list:l0 level1 lfo1"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-theme-font:minor-fareast; mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-theme-font: minor-fareast">$$<span lang="EN-US">+4=5+2<o:p></o:p></span></span></p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152873",
                    "content":"3",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152873",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                }
            ]
        },
        {
            "questionID":60585,
            "content":"<p>6-$$=7-3</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152871",
                    "content":"2",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152871",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                }
            ]
        },
        {
            "questionID":60584,
            "content":"<p>2+$$=6-1</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152869",
                    "content":"3",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152869",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                }
            ]
        },
        {
            "questionID":60583,
            "content":"<p>7-$$=6-5</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152867",
                    "content":"6",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152867",
                    "answerContentHtml":"6",
                    "answerContent":"6"
                }
            ]
        },
        {
            "questionID":60582,
            "content":"<p>$$+0=7-1</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152865",
                    "content":"6",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152865",
                    "answerContentHtml":"6",
                    "answerContent":"6"
                }
            ]
        },
        {
            "questionID":60581,
            "content":"<p>$$+3=6+1</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152863",
                    "content":"4",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152863",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                }
            ]
        },
        {
            "questionID":60580,
            "content":"<p>5-$$=2+3</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152861",
                    "content":"0",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152861",
                    "answerContentHtml":"0",
                    "answerContent":"0"
                }
            ]
        },
        {
            "questionID":60579,
            "content":"<p>4+1=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152859",
                    "content":"5",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152859",
                    "answerContentHtml":"5",
                    "answerContent":"5"
                }
            ]
        },
        {
            "questionID":60578,
            "content":"<p>7-5=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152857",
                    "content":"2",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152857",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                }
            ]
        },
        {
            "questionID":60577,
            "content":"<p>4+3=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152855",
                    "content":"7",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152855",
                    "answerContentHtml":"7",
                    "answerContent":"7"
                }
            ]
        },
        {
            "questionID":60576,
            "content":"<p>7-3=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152853",
                    "content":"4",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152853",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                }
            ]
        },
        {
            "questionID":60575,
            "content":"<p>3+4=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152851",
                    "content":"7",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152851",
                    "answerContentHtml":"7",
                    "answerContent":"7"
                }
            ]
        },
        {
            "questionID":60574,
            "content":"<p>5+1=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152849",
                    "content":"6",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152849",
                    "answerContentHtml":"6",
                    "answerContent":"6"
                }
            ]
        },
        {
            "questionID":60573,
            "content":"<p>5-1=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152847",
                    "content":"4",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152847",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                }
            ]
        },
        {
            "questionID":60572,
            "content":"<p>7-1=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152845",
                    "content":"6",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152845",
                    "answerContentHtml":"6",
                    "answerContent":"6"
                }
            ]
        },
        {
            "questionID":60571,
            "content":"<p>2+4=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152843",
                    "content":"6",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152843",
                    "answerContentHtml":"6",
                    "answerContent":"6"
                }
            ]
        },
        {
            "questionID":60570,
            "content":"<p>2+5=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152841",
                    "content":"7",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152841",
                    "answerContentHtml":"7",
                    "answerContent":"7"
                }
            ]
        },
        {
            "questionID":60569,
            "content":"<p>1+4=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152839",
                    "content":"5",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152839",
                    "answerContentHtml":"5",
                    "answerContent":"5"
                }
            ]
        },
        {
            "questionID":60568,
            "content":"<p>4-1=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152837",
                    "content":"3",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152837",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                }
            ]
        },
        {
            "questionID":60567,
            "content":"<p>6-2=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152835",
                    "content":"4",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152835",
                    "answerContentHtml":"4",
                    "answerContent":"4"
                }
            ]
        },
        {
            "questionID":60566,
            "content":"<p>3-1=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152833",
                    "content":"2",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152833",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                }
            ]
        },
        {
            "questionID":60565,
            "content":"<p>7-4=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152831",
                    "content":"3",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152831",
                    "answerContentHtml":"3",
                    "answerContent":"3"
                }
            ]
        },
        {
            "questionID":60564,
            "content":"<p>7-2=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152829",
                    "content":"5",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152829",
                    "answerContentHtml":"5",
                    "answerContent":"5"
                }
            ]
        },
        {
            "questionID":60563,
            "content":"<p>4+2=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152827",
                    "content":"6",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152827",
                    "answerContentHtml":"6",
                    "answerContent":"6"
                }
            ]
        },
        {
            "questionID":60562,
            "content":"<p>4-2=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152825",
                    "content":"2",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152825",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                }
            ]
        },
        {
            "questionID":60561,
            "content":"<p>3+3=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152823",
                    "content":"6",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152823",
                    "answerContentHtml":"6",
                    "answerContent":"6"
                }
            ]
        },
        {
            "questionID":60560,
            "content":"<p>6-4=$$</p>",
            "typeID":3,
            "accuracy":100,
            "subjectId":12455,
            "hardId":0,
            "answers":[
                {
                    "answerID":"152821",
                    "content":"2",
                    "sign":"A",
                    "isright":2
                }
            ],
            "rightSelectContentList":[
                {
                    "answerID":"152821",
                    "answerContentHtml":"2",
                    "answerContent":"2"
                }
            ]
        }
    ]
}